experiment:
  name: scan_pairs
  seed: 11
  output_root: outputs/runs
dataset:
  mode: file
  path: data/raw/sec_vul_eval-train.arrow
  sample_selection: standard
  project_exclude:
    - linux
    - Chrome
    - tensorflow
    - Android
  pair_require_same_function: true
  pair_require_same_file: true
logging:
  level: INFO
  rich: true
  profile_memory: true
  profile_time: true
